version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  server:
    build:
      context: ./Server
    ports:
      - "4000:4000"
    env_file:
      - ./Server/.env
    depends_on:
      - redis

  image-ui:
    build:
      context: ./image-ui
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  redis_data:
